### ISSUE TITLE
Roadmap for now

### ISSUE THREAD

**Issue by alexpyattaev** [alexpyattaev/roc-plugin-example#3]
- [ ] feature request for platform defined datastructures
- [ ] finish dynamic loading into bevy (AP)
- [ ] get the Model from gui example translated into plugin state (and fix glue accordingly)
- [ ] Patch Tasks into Bevy Commands
